# Site settings
name: Notes
email: cailiuzhaung@gmail.com
author: Mista Cai
url: https://fgroove.github.io
resume_site: https://fgroove.github.io
github: https://github.com/fgroove/
baseurl: ''
description: Keep Simple!
meta_description: notes, snippets
motto: 简单的活着
banner: Don't panic, be yourself!

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Fgroove

# Build settings
markdown: kramdown



theme: jekyll-theme-leap-day